version: "2.1"
networks:
  internal_network:
services:      
  db:
#    image: repo.ambar.cloud:443/ambar-mongodb:2.1
    image: ${DOCKER_REGISTRY}/ambar-mongodb:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./MongoDB
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    environment:
      - cacheSizeGB=2
    volumes:
      - db-data:/data/db
    expose:
      - "27017"   
    networks:
      - internal_network
  es:
#    image: repo.ambar.cloud:443/ambar-es:2.1
    image: ${DOCKER_REGISTRY}/ambar-es:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./ElasticSearch
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    ports:
      - "${PORT_ES_1:-9200}:9200"
      - "${PORT_ES_2:-9300}:9300"
    expose:
      - "9200" 
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - internal_network
  kibana:
#    image: kibana:5.6.3
    image: ${DOCKER_REGISTRY}/ambar-kibana:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./Kibana
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    ports:
      - "${PORT_KIBANA:-5601}:5601"
    depends_on:
      es:
        condition: service_healthy
    links:
      - es:elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 30s
      retries: 50
    networks:
      - internal_network
  rabbit:
#    image: repo.ambar.cloud:443/ambar-rabbit:2.1
    image: ${DOCKER_REGISTRY}/ambar-rabbit:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./Rabbit
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    hostname: rabbit
    expose:
      - "15672"
      - "5672"   
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    networks:
      - internal_network
  redis:
#    image: repo.ambar.cloud:443/ambar-redis:2.1
    image: ${DOCKER_REGISTRY}/ambar-redis:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./Redis
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    expose:
      - "6379" 
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal_network
  serviceapi:
#    image: repo.ambar.cloud:443/ambar-serviceapi:2.1
    image: ${DOCKER_REGISTRY}/ambar-serviceapi:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./ServiceApi
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=${langAnalyzer}  
      - SLAO_HOSTNAME=ambar 
      - SLAO_API_KEY=
    expose:
      - "8081"  
    networks:
      - internal_network
  webapi:
#    image: repo.ambar.cloud:443/ambar-webapi:2.1
    image: ${DOCKER_REGISTRY}/ambar-webapi:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./WebApi
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    depends_on:
      serviceapi:
        condition: service_healthy
    environment:            
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit  
      - SLAO_HOSTNAME=ambar
      - SLAO_API_KEY=  
    ports:
      - "${PORT_WEBAPI:-8080}:8080"
    expose:
      - "8080"
    networks:
      - internal_network
  frontend:
#    image: repo.ambar.cloud:443/ambar-frontend:2.1
    image: ${DOCKER_REGISTRY}/ambar-frontend:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./FrontEnd
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    depends_on:
      webapi:
        condition: service_healthy
    ports:
      - "${PORT_FRONTENT:-80}:80"
    expose:
      - "80"
    environment:
      - api=http://${ambarHostIpAddress}:${PORT_WEBAPI:-8080}
    networks:
      - internal_network
  pipeline0:
#    image: repo.ambar.cloud:443/ambar-pipeline:2.1
    image: ${DOCKER_REGISTRY}/ambar-pipeline:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./Pipeline
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    depends_on: 
      serviceapi: 
        condition: service_healthy                            
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
    networks:
      - internal_network  
  my-crawler:
#    image: repo.ambar.cloud:443/ambar-local-crawler:2.1
    image: ${DOCKER_REGISTRY}/ambar-local-crawler:2.1${DOCKER_IMAGE_VERSION}
    restart: always
    build:
      context: ./LocalCrawler
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - NO_PROXY=${NO_PROXY}
    depends_on: 
      webapi: 
#      serviceapi: 
        condition: service_healthy 
      pipeline0:
        condition: service_healthy
    links:
        - webapi:serviceapi
    expose:
      - "8082"
    environment:      
      - name=my-crawler
      - ignoreFolders=**/?(ForSharing|.*)/**
      - ignoreExtensions=.{exe,dll,rar}
      - ignoreFileNames=?(*backup*|.*)
      - maxFileSize=15mb
    volumes:
      - ${pathToCrawl}:/usr/data
    networks:
      - internal_network


volumes:
   db-data:
   es-data:
   rabbit-data:
  
